### ISSUE TITLE
[Bug] Exception when updating

### ISSUE THREAD

**Issue by jobobby04** [Suwayomi/Tachidesk-Server#257]
## Device information
- Tachidesk version: Commit 1043
- Server Operating System: Windows 10
- Server Desktop Environment: Windows 10
- Server JVM version: JDK 15.0.2
- Client Operating System: Windows 10
- Client Web Browser: TachideskJUI

## Steps to reproduce
1. Connect a websocket to the updates endpoint
2. Launch the updater

### Expected behavior
The updater runs though the manga and finishes properly

### Actual behavior
Sometimes it throws an exception that totally stops the updater

## Other details
I used a partial implementation of updates to test this in TachideskJUI.
```kotlin
Got an exception when testing the updater in JUI using the latest server commit
19:29:59.801 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server: Exception in thread "DefaultDispatcher-worker-10" java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
19:29:59.801 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at java.base/java.util.LinkedHashMap.valuesToArray(LinkedHashMap.java:555)
19:29:59.801 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at java.base/java.util.LinkedHashMap$LinkedValues.toArray(LinkedHashMap.java:635)
19:29:59.801 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
19:29:59.801 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1333)
19:29:59.801 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1314)
19:29:59.801 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at suwayomi.tachidesk.manga.impl.update.Updater.process(Updater.kt:43)
19:29:59.801 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at suwayomi.tachidesk.manga.impl.update.Updater.access$process(Updater.kt:17)
19:29:59.802 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at suwayomi.tachidesk.manga.impl.update.Updater$createUpdateJob$1.invokeSuspend(Updater.kt:34)
19:29:59.802 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
19:29:59.802 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
19:29:59.802 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
19:29:59.802 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
19:29:59.802 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
19:29:59.802 [DefaultDispatcher-worker-4 @coroutine#9] INFO/Server:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) 

```

**Comment by Vikng412** [comment]
can you tell me how do you update the library in tachidesk, like you do in tachiyomi app on android by swiping down?
